server:
  port: 8080

spring:
  application.name: loco-back
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari.schema: ${DB_SCHEMA:loco}
  jpa:
    hibernate.ddl-auto: ${HIBERNATE_MIGRATION:none}
    show-sql: false
    properties.hibernate:
      format_sql: true
      default_schema: ${DB_SCHEMA:loco}
  servlet:
    multipart:
      max-file-size: 10MB

yandex:
  exchange-url: https://oauth.yandex.ru/token
  client-secret: ${YANDEX_CLIENT_SECRET:yandex-client-secret}
  client-id: ${YANDEX_CLIENT_ID:yandex-client-id}
  info-url: https://login.yandex.ru/info?format=jwt
  issuer-uri: ${YANDEX_ISSUER_URL:login.yandex.ru}
vk:
  exchange-url: https://id.vk.ru/oauth2/auth
  redirect-uri: ${VK_REDIRECT_URI:vk-redirect-uri}
  client-secret: ${VK_CLIENT_SECRET:vk-client-secret}
  client-id: ${VK_CLIENT_ID:vk-client-id}
  info-url: https://id.vk.ru/oauth2/user_info
  issuer-uri: ${VK_ISSUER:VK}

filestore:
  local-store-path: ${LOCAL_STORE_PATH:../store/}}